Add client_secret_basic and client_secret_jwt auth methods #101
enonic/app-oidc-idprovider pull request #102
Opened 2022-10-03 14:00 UTC by vbradnitski

2022-10-03 16:05 UTC, rymsha approved these changes

2022-10-03 16:05 UTC, rymsha commented on README.adoc
> +This ID Provider application follows the Authorization Code Flow and uses one of the Client/Secret POST, Basic or JWT token auth methods.
```suggestion
This ID Provider application follows the Authorization Code Flow and uses one of the `client_secret_post`, `client_secret_basic` or `client_secret_jwt` auth methods.
```

2022-10-03 16:05 UTC, rymsha commented on src/main/resources/idprovider/idprovider.xml
> +            <option value="jwt">Jwt</option>
```suggestion
            <option value="jwt">JWT</option>
```

2022-10-03 17:43 UTC, rymsha requested changes

2022-10-03 17:43 UTC, rymsha commented on src/main/resources/lib/oidc.js
> +               + '&code=' + code
Parameters must be encoded

2022-10-04 10:59 UTC, rymsha approved these changes

2022-10-04 12:21 UTC, merged

2022-10-04 12:25 UTC, anatol-sialitski approved these changes